# MMA Fights Data Analysis
This notebook provides an analysis of the MMA fights dataset, focusing on cleaning the data by removing duplicates and filtering fights for the top 100 fighters based on their career stats.
### Key Tasks
- Data Loading
- Data Cleaning (Remove duplicates)
- Filter Fights for Top 100 Fighters
- Display Relevant Fights

In [8]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Load the fights dataset
fights_df = pd.read_csv('../Data/Raw/Pro_MMA_Fights.csv')

# Display the first few rows of the dataset
fights_df.head()

,event_title,organisation,date,location,match_nr,fighter1_name,fighter2_name,fighter1_result,fighter2_result,win_method,win_details,round,time
0,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",13,Ciryl Gane,Derrick Lewis,win,loss,TKO,Punches,3,4:11
1,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",12,Jose Aldo,Pedro Munhoz,win,loss,Decision,Unanimous,3,05:00
2,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",11,Vicente Luque,Michael Chiesa,win,loss,Submission,Brabo Choke,1,03:25
3,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",10,Tecia Torres,Angela Hill,win,loss,Decision,Unanimous,3,05:00
4,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",9,Yadong Song,Casey Kenney,win,loss,Decision,Split,3,05:00

## Data Cleaning
In this section, we will clean the data by removing any duplicate entries from the dataset.

In [9]:
# Remove duplicates from the fights dataset
fights_df_clean = fights_df.drop_duplicates()

# Display the cleaned dataset
fights_df_clean.head()

,event_title,organisation,date,location,match_nr,fighter1_name,fighter2_name,fighter1_result,fighter2_result,win_method,win_details,round,time
0,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",13,Ciryl Gane,Derrick Lewis,win,loss,TKO,Punches,3,4:11
1,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",12,Jose Aldo,Pedro Munhoz,win,loss,Decision,Unanimous,3,05:00
2,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",11,Vicente Luque,Michael Chiesa,win,loss,Submission,Brabo Choke,1,03:25
3,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",10,Tecia Torres,Angela Hill,win,loss,Decision,Unanimous,3,05:00
4,UFC 265 - Lewis vs. Gane,Ultimate Fighting Championship (UFC),"Aug 7, 2021","Toyota Center, Houston, Texas, United States",9,Yadong Song,Casey Kenney,win,loss,Decision,Split,3,05:00

## Filter Fights for Top 100 Fighters
Now, we will filter the fights to show only those involving the top 100 fighters based on their career stats. We will filter by fighter names, assuming the 'name' column exists in both datasets.

In [14]:
# Load the top 100 fighters list from the previously created DataFrame (fighters_df)
top_100_fighters = pd.read_csv('../Data/Processed/Top_100_MMA_Fighters.csv')  # Assuming top 100 fighters DataFrame

# Filter fights that involve the top 100 fighters
fights_top_100 = fights_df_clean[
    (fights_df_clean['fighter1_name'].isin(top_100_fighters['fighter_name'])) |
    (fights_df_clean['fighter2_name'].isin(top_100_fighters['fighter_name']))
]

# Display the filtered dataset for the top 100 fighters
fights_top_100.head()

,event_title,organisation,date,location,match_nr,fighter1_name,fighter2_name,fighter1_result,fighter2_result,win_method,win_details,round,time
26,UFC on ESPN 27 - Sandhagen vs. Dillashaw,Ultimate Fighting Championship (UFC),"Jul 24, 2021","UFC Apex, Las Vegas, Nevada, United States",8,Maycee Barber,Miranda Maverick,win,loss,Decision,Split,3,05:00
34,UFC on ESPN 26 - Makhachev vs. Moises,Ultimate Fighting Championship (UFC),"Jul 17, 2021","UFC Apex, Las Vegas, Nevada, United States",10,Islam Makhachev,Thiago Moises,win,loss,Submission,Rear-Naked Choke,4,2:38
36,UFC on ESPN 26 - Makhachev vs. Moises,Ultimate Fighting Championship (UFC),"Jul 17, 2021","UFC Apex, Las Vegas, Nevada, United States",8,Mateusz Gamrot,Jeremy Stephens,win,loss,Submission,Kimura,1,01:05
48,UFC 264 - Poirier vs. McGregor 3,Ultimate Fighting Championship (UFC),"Jul 10, 2021","T-Mobile Arena, Las Vegas, Nevada, United States",8,Sean O'Malley,Kris Moutinho,win,loss,TKO,Punches,3,04:33
51,UFC 264 - Poirier vs. McGregor 3,Ultimate Fighting Championship (UFC),"Jul 10, 2021","T-Mobile Arena, Las Vegas, Nevada, United States",5,Ilia Topuria,Ryan Hall,win,loss,KO,Punches,1,04:47

In [16]:
# Save the filtered dataset for the top 100 fighters to a new CSV file
fights_top_100.to_csv('../Data/Processed/Fights_Top_100_Fighters.csv', index=False)

## Conclusion
This analysis cleaned the MMA fights dataset by removing duplicates and filtered fights involving the top 100 fighters based on their career performance. The next steps could involve further analysis of these fights or predictive modeling based on these fights.